###
POST http://localhost:5000/sites/park HTTP/1.1
Content-Type: im

{
    "number": 13,
    "name": "Pepino",
    "avaliable": true,
    "date": ""
}
###
GET http://localhost:5000/sites/park/5 HTTP/1.1
###
PUT http://localhost:5000/sites/park/ HTTP/1.1
Content-Type: application/json

{
    "avaliable": false,
    "name": "harryng"
}
###
DELETE http://localhost:5000/sites/park/ HTTP/1.1
###
DELETE http://localhost:5000/sites/park/15 HTTP/1.1

###
POST http://localhost:5000/users/send HTTP/1.1
Content-Type: application/json

{
    "name": "Albin",
    "age": 30,
    "dni": 3674955,
    "phone":"1234641",
    "mail":"albin92@gmail.com"
}
###
GET http://localhost:5000/users/ HTTP/1.1
###
DELETE http://localhost:5000/users/delet/Albin HTTP/1.1

###
PUT http://localhost:5000/users/Albin HTTP/1.1
Content-Type: application/json

{
    "name": "Federico",
    "age": 32
}